title: 沐雨橙舟の秘密基地
email: muzhou233@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
keyword: 'MuZhou, MuZhou Blog, OIer, noip'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://mosarin.tech' # the base hostname & protocol for your site, e.g. http://example.com

# About/contact
owner:
    name: '沐雨橙舟'
    email: 'MuZhou233@outlook.com'
    bio: ''

# Data
avatar: /asserts/img/avatar.jpg
favicon: /favicon.jpg
music:
    title: なつめ千秋,GUMI - センチメンタルな愛慕心
    url: /asserts/lib/plyr/test.mp3

# Build settings
# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

markdown: kramdown

highlighter: rouge
permalink: pretty
paginate: 16

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - README.md

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone: Asia/Shanghai

# Gems
plugins: [jekyll-paginate]
